apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-image
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-storage
  source:
    http:
      url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: vm1
spec:
  running: true
  dataVolumeTemplates:
    - metadata:
        name: vm1
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
          storageClassName: local-storage
        source:
          pvc:
            name: ubuntu-image
            namespace: example
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1
    spec:
      hostname: vm1
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
            bootOrder: 1
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
            bootOrder: 2
          interfaces:
          - name: default
            masquerade: {}
            bootOrder: 3
          # - name: underlay
          #   bridge: {}
          #   bootOrder: 4
        machine:
          type: q35
        resources:
          requests:
            memory: 4096M
      networks:
      - name: default
        pod: {}
      # - name: underlay
      #   multus:
      #     networkName: kube-public/underlay-bridge
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: vm1
      - cloudInitNoCloud:
          # openssl passwd -6 -salt=salt password
          userData: |
            #cloud-config
            hostname: vm1
            users:
            - name: onoe
              ssh_import_id: gh:hiroyaonoe
              lock_passwd: false
              passwd: $6$salt$IxDD3jeSOb5eB1CX5LBsqZFVkJdido3OUILO5Ifz5iwMuTS4XMS130MTSuDDl3aCI6WouIL9AjRbLCelDCy.g.
              shell: /bin/bash
              sudo: ALL=(ALL) NOPASSWD:ALL
              uid: 1000
            ssh_pwauth: true
            disable_root: false
          networkData: |
            version: 2
            ethernets:
              enp1s0:
                dhcp4: true
              net1:
                dhcp4: false
                addresses: [192.168.0.161/24]
                gateway4: 192.168.0.1
        name: cloudinitdisk
---
apiVersion: v1
kind: Service
metadata:
  name: vm1-ssh
spec:
  type: NodePort
  selector:
    kubevirt.io/domain: vm1
  ports:
  - nodePort: 30322
    port: 22
    protocol: TCP
    targetPort: 22
