apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      hostname: testvm
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinitdisk
              disk:
                bus: virtio
              bootOrder: 2
          interfaces:
          - name: default
            masquerade: {}
            bootOrder: 3
          - name: underlay
            bridge: {}
            bootOrder: 4
        resources:
          requests:
            memory: 4096M
      networks:
      - name: default
        pod: {}
      - name: underlay
        multus:
          networkName: kube-public/underlay-bridge
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            # openssl passwd -6 -salt=salt password
            userData: |
              #cloud-config
              hostname: testvm
              users:
              - name: onoe
                ssh_import_id: gh:hiroyaonoe
                lock_passwd: false
                passwd: $6$salt$IxDD3jeSOb5eB1CX5LBsqZFVkJdido3OUILO5Ifz5iwMuTS4XMS130MTSuDDl3aCI6WouIL9AjRbLCelDCy.g.
                shell: /bin/bash
                sudo: ALL=(ALL) NOPASSWD:ALL
                uid: 1000
              ssh_pwauth: true
              disable_root: false
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
                enp2s0:
                  dhcp4: false
                  addresses: [192.168.0.160/24]
                  gateway4: 192.168.0.1
---
