apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: underlay-bridge
  namespace: kube-public
  annotations:
    # https://access.redhat.com/documentation/ja-jp/openshift_container_platform/4.1/html/container-native_virtualization/attaching-to-multiple-networks#connecting-resource-bridge-network_cnv-attaching-multiple-networks
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br0
spec:
  # https://www.cni.dev/plugins/current/main/bridge/#example-configuration
  # https://www.cni.dev/plugins/v1.1/ipam/host-local/
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "underlay-bridge",
      "type": "bridge",
      "bridge": "br0",
      "ipam": {
          "type": "host-local",
          "subnet": "192.168.0.0/24"
      }
    }
