resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- app-of-apps.yaml
- ingress.yaml
- service-monitor.yaml
- sa-token.yaml

patchesStrategicMerge:
- overlays/argocd-cm.yaml
- overlays/argocd-server.yaml
