apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # private repoじゃないから不要？
  repositories: |
    - name: my-k8s-cluster
      type: git
      url: https://github.com/hiroyaonoe/my-k8s-cluster.git
