# https://docs.cilium.io/en/stable/gettingstarted/kind/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.11.6
    helm:
      releaseName: cilium
      values: |
        kubeProxyReplacement: partial
        hostServices:
          enabled: false
        externalIPs:
          enabled: true
        nodePort:
          enabled: true
        hostPort:
          enabled: true
        bpf:
          masquerade: false
        image:
          pullPolicy: IfNotPresent
        ipam:
          mode: kubernetes
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
