apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
spec:
  project: default
  source:
    repoURL: https://github.com/hiroyaonoe/my-k8s-cluster.git
    targetRevision: main
    path: argocd/manifests/elastic
  destination:
    server: "https://kubernetes.default.svc"
