apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.1.4
    helm:
      releaseName: nginx
      values: |
        ingressClassResource:
          # -- Is this the default ingressClass for the cluster
          default: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
