apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
spec:
  project: default
  source:
    repoURL: https://github.com/hiroyaonoe/my-k8s-cluster.git
    targetRevision: main
    path: argocd/manifests/kubevirt
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubevirt
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
