# https://opentelemetry.io/docs/kubernetes/getting-started/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
spec:
  project: default
  source:
    # https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector
    chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts/
    targetRevision: 0.96.0
    helm:
      releaseName: opentelemetry-collector
      # https://www.elastic.co/guide/en/observability/current/apm-open-telemetry-direct.html#apm-connect-open-telemetry-collector
      # https://www.elastic.co/guide/en/apm/guide/7.17/open-telemetry.html
      valuesObject:
        mode: daemonset
        image:
          repository: otel/opentelemetry-collector-k8s
        command:
          name: otelcol-k8s
        service:
          # Enable the creation of a Service.
          # By default, it's enabled on mode != daemonset.
          # However, to enable it on mode = daemonset, its creation must be explicitly enabled
          enabled: true
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                http:
          exporters:
            debug:
              verbosity: detailed
            otlp/elastic: 
              # Elastic APM server https endpoint without the "https://" prefix
              endpoint: log-apm-http.log.svc.cluster.local:8200
              tls:
                insecure: true
              headers:
                # Elastic APM Server secret token
                # kubectl get secret/log-apm-token -o go-template='{{index .data "secret-token" | base64decode}}' -n log
                Authorization: "Bearer Bii14lZY969c3T4D48DNp0dg"
          processors: 
            batch: {}
            memory_limiter:
              check_interval: 1s
              limit_mib: 2000
          service:
            pipelines:
              metrics:
                exporters:
                  - debug
                  - otlp/elastic
                processors:
                  - memory_limiter
                  - batch
                receivers:
                  - otlp
              traces:
                exporters:
                  - debug
                  - otlp/elastic
                processors:
                  - memory_limiter
                  - batch
                receivers:
                  - otlp
  destination:
    server: "https://kubernetes.default.svc"
    namespace: otel-collector
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
