apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
spec:
  project: default
  source:
    # https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-demo
    chart: opentelemetry-demo
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts/
    targetRevision: 0.32.0
    helm:
      releaseName: opentelemetry-demo
      valuesObject:
        opentelemetry-collector:
          enabled: false
        jaeger:
          enabled: false
        prometheus:
          enabled: false
        grafana:
          enabled: false
        default:
          # Allows overriding and additions to .Values.default.env
          envOverrides:
            - name: OTEL_COLLECTOR_NAME
              value: opentelemetry-collector.otel-collector.svc.cluster.local
        components:
          frontendProxy:
            # Ingresses rules to add for the to the component
            ingress:
            # Enable the creation of Ingress rules. Default is false
              enabled: true
            # Annotations to add to the ingress rule
              annotations: {}
            # Hosts definitions for the Ingress rule
              hosts:
                - host: otel-demo.k8s.internal.onoe.dev
            # Each host can have multiple paths/routes
                  paths:
                    - path: /
                      pathType: Prefix
                      port: 8080
            # Optional TLS specifications for the Ingress rule
              tls:
                - secretName: demo-tls
                  hosts:
                    - otel-demo.k8s.internal.onoe.dev
          accountingService:
            resources:
              requests:
                memory: "50Mi"
              limits:
                memory: "200Mi"
          flagd:
            resources:
              requests:
                memory: "50Mi"
              limits:
                memory: "200Mi"
          productCatalogService:
            resources:
              requests:
                memory: "20Mi"
              limits:
                memory: "200Mi"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: otel-demo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
