apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config
spec:
  project: default
  source:
    repoURL: https://github.com/hiroyaonoe/my-k8s-cluster.git
    targetRevision: main
    path: argocd/manifests/vault-config
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
