# https://github.com/kubevirt/kubevirt/releases/download/v1.2.2/kubevirt-cr.yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    network:
      # https://kubevirt.io/user-guide/network/interfaces_and_networks/#bridge
      permitBridgeInterfaceOnPodNetwork: false
    developerConfiguration:
      featureGates:
      # https://kubevirt.io/user-guide/storage/disks_and_volumes/#disk-expansion
      - ExpandDisks
  imagePullPolicy: IfNotPresent
  customizeComponents: {}
  workloadUpdateStrategy: {}
  certificateRotateStrategy: {}
