# https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html
resources:
  - https://download.elastic.co/downloads/eck/2.13.0/crds.yaml
  - https://download.elastic.co/downloads/eck/2.13.0/operator.yaml
