resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.1/deploy/static/provider/kind/deploy.yaml

patchesStrategicMerge:
- overlays/ingress-class.yaml
- overlays/service.yaml
- overlays/deployment.yaml
