# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/README.md#prometheus-metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-controller
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx-controller-metrics
  endpoints:
  - port: metrics
