apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-dashboard
  labels:
    grafana_dashboard: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-dashboard
  labels:
    grafana_dashboard: "1"
